version: '3.8'
services:
  db:
    build: .
    container_name: bd
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
