services:
  db:
    image: postgres:latest
    container_name: bd
    environment:
      POSTGRES_DB: biblioteca
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
